from pymongo import MongoClient

# Replace the following URI with your actual MongoDB connection string
uri = "mongodb://localhost:27017"

client = MongoClient(uri)

# Access a specific database
db = client['jobs']

job_listing = db['job_listing']

# Insert job listings
job_listing.insert_many([
  {
    "company_name": "ABC Tech Solutions",
    "job_name": "Software Engineer",
    "job_description": "Develop and maintain web applications using modern technologies.",
    "duration": "Full-time",
    "when_needed": "ASAP",
    "average_pay": "$80,000 per year",
    "part_time": False,
    "location": "New York, USA",
    "latitude": 40.7128,
    "longitude": -74.0060
  },
  {
    "company_name": "Global Marketing Agency",
    "job_name": "Digital Marketing Specialist",
    "job_description": "Create and manage online marketing campaigns for clients.",
    "duration": "Full-time",
    "when_needed": "2 weeks from now",
    "average_pay": "$55,000 per year",
    "part_time": False,
    "location": "London, UK",
    "latitude": 51.5074,
    "longitude": -0.1278
  },
  {
    "company_name": "Healthcare Innovations Ltd.",
    "job_name": "Registered Nurse",
    "job_description": "Provide medical care and support to patients in a hospital setting.",
    "duration": "Full-time",
    "when_needed": "Immediate",
    "average_pay": "$60,000 per year",
    "part_time": False,
    "location": "Toronto, Canada",
    "latitude": 43.651070,
    "longitude": -79.347015
  },
  {
    "company_name": "EcoTech Solutions",
    "job_name": "Environmental Scientist",
    "job_description": "Conduct research on environmental issues and develop sustainable solutions.",
    "duration": "Full-time",
    "when_needed": "1 month from now",
    "average_pay": "$70,000 per year",
    "part_time": False,
    "location": "Sydney, Australia",
    "latitude": -33.8688,
    "longitude": 151.2093
  },
  {
    "company_name": "Fintech Innovations",
    "job_name": "Financial Analyst",
    "job_description": "Analyze financial data and provide insights for investment decisions.",
    "duration": "Full-time",
    "when_needed": "ASAP",
    "average_pay": "$65,000 per year",
    "part_time": False,
    "location": "Singapore",
    "latitude": 1.3521,
    "longitude": 103.8198
  },
  {
    "company_name": "Artistic Creations Inc.",
    "job_name": "Graphic Designer",
    "job_description": "Create visual designs and artwork for various projects.",
    "duration": "Part-time",
    "when_needed": "3 weeks from now",
    "average_pay": "$30,000 per year (part-time)",
    "part_time": True,
    "location": "Paris, France",
    "latitude": 48.8566,
    "longitude": 2.3522
  },
  {
    "company_name": "Tech Innovations Ltd.",
    "job_name": "IT Support Specialist",
    "job_description": "Provide technical support and assistance to end-users.",
    "duration": "Full-time",
    "when_needed": "Immediate",
    "average_pay": "$45,000 per year",
    "part_time": False,
    "location": "Berlin, Germany",
    "latitude": 52.5200,
    "longitude": 13.4050
  },
  {
    "company_name": "EduPro Learning Center",
    "job_name": "Tutor (Mathematics)",
    "job_description": "Teach mathematics to students of various age groups.",
    "duration": "Part-time",
    "when_needed": "2 weeks from now",
    "average_pay": "$25 per hour (part-time)",
    "part_time": True,
    "location": "Tokyo, Japan",
    "latitude": 35.682839,
    "longitude": 139.759455
  },
  {
    "company_name": "Travel Adventures Ltd.",
    "job_name": "Travel Consultant",
    "job_description": "Assist customers in planning and booking their travel adventures.",
    "duration": "Full-time",
    "when_needed": "ASAP",
    "average_pay": "$40,000 per year",
    "part_time": False,
    "location": "Cape Town, South Africa",
    "latitude": -33.9249,
    "longitude": 18.4241
  },
  {
    "company_name": "Energy Solutions Co.",
    "job_name": "Renewable Energy Engineer",
    "job_description": "Design and implement renewable energy projects for a sustainable future.",
    "duration": "Full-time",
    "when_needed": "1 month from now",
    "average_pay": "$75,000 per year",
    "part_time": False,
    "location": "São Paulo, Brazil",
    "latitude": -23.5505,
    "longitude": -46.6333
  },
  {
    "company_name": "Innovative Robotics Inc.",
    "job_name": "Robotics Engineer",
    "job_description": "Design and develop robotic systems for automation and manufacturing.",
    "duration": "Full-time",
    "when_needed": "Immediate",
    "average_pay": "$85,000 per year",
    "part_time": False,
    "location": "Shanghai, China",
    "latitude": 31.2304,
    "longitude": 121.4737
  },
  {
    "company_name": "Digital Media Productions",
    "job_name": "Video Editor",
    "job_description": "Edit and produce high-quality video content for online platforms.",
    "duration": "Part-time",
    "when_needed": "2 weeks from now",
    "average_pay": "$35,000 per year (part-time)",
    "part_time": True,
    "location": "Mumbai, India",
    "latitude": 19.0760,
    "longitude": 72.8777
  },
  {
    "company_name": "BioPharma Research Institute",
    "job_name": "Biomedical Research Scientist",
    "job_description": "Conduct research in the field of biomedical sciences and contribute to breakthroughs in healthcare.",
    "duration": "Full-time",
    "when_needed": "ASAP",
    "average_pay": "$70,000 per year",
    "part_time": False,
    "location": "Zurich, Switzerland",
    "latitude": 47.3769,
    "longitude": 8.5417
  },
  {
    "company_name": "Creative Marketing Agency",
    "job_name": "Content Writer",
    "job_description": "Create engaging content for marketing campaigns and websites.",
    "duration": "Part-time",
    "when_needed": "3 weeks from now",
    "average_pay": "$28,000 per year (part-time)",
    "part_time": True,
    "location": "Rio de Janeiro, Brazil",
    "latitude": -22.9068,
    "longitude": -43.1729
  },
  {
    "company_name": "TechStart Innovations",
    "job_name": "Cybersecurity Analyst",
    "job_description": "Protect the company's digital assets by analyzing and securing computer systems.",
    "duration": "Full-time",
    "when_needed": "Immediate",
    "average_pay": "$75,000 per year",
    "part_time": False,
    "location": "Toronto, Canada",
    "latitude": 43.651070,
    "longitude": -79.347015
  },
  {
    "company_name": "Fashion Forward Designs",
    "job_name": "Fashion Designer",
    "job_description": "Create stylish clothing and accessories for the fashion industry.",
    "duration": "Full-time",
    "when_needed": "ASAP",
    "average_pay": "$50,000 per year",
    "part_time": False,
    "location": "Milan, Italy",
    "latitude": 45.4642,
    "longitude": 9.1900
  },
  {
    "company_name": "Digital Health Solutions",
    "job_name": "Telehealth Nurse",
    "job_description": "Provide medical advice and support to patients through telehealth services.",
    "duration": "Part-time",
    "when_needed": "2 weeks from now",
    "average_pay": "$32,000 per year (part-time)",
    "part_time": True,
    "location": "Sydney, Australia",
    "latitude": -33.8688,
    "longitude": 151.2093
  },
  {
    "company_name": "Urban Planning Consultants",
    "job_name": "Urban Planner",
    "job_description": "Develop sustainable urban plans and infrastructure projects.",
    "duration": "Full-time",
    "when_needed": "1 month from now",
    "average_pay": "$65,000 per year",
    "part_time": False,
    "location": "Munich, Germany",
    "latitude": 48.1351,
    "longitude": 11.5820
  },
  {
    "company_name": "Green Energy Corporation",
    "job_name": "Solar Energy Technician",
    "job_description": "Install and maintain solar energy systems for residential and commercial clients.",
    "duration": "Full-time",
    "when_needed": "Immediate",
    "average_pay": "$45,000 per year",
    "part_time": False,
    "location": "Los Angeles, USA",
    "latitude": 34.0522,
    "longitude": -118.2437
  },
  {
    "company_name": "Global Charity Foundation",
    "job_name": "Fundraising Coordinator",
    "job_description": "Organize and lead fundraising campaigns for charitable causes.",
    "duration": "Part-time",
    "when_needed": "3 weeks from now",
    "average_pay": "$30,000 per year (part-time)",
    "part_time": True,
    "location": "Nairobi, Kenya",
    "latitude": -1.286389,
    "longitude": 36.817223
  },
  {
    "company_name": "Space Exploration Technologies",
    "job_name": "Astronaut",
    "job_description": "Participate in space missions, conduct research, and operate spacecraft.",
    "duration": "Full-time",
    "when_needed": "ASAP",
    "average_pay": "$100,000 per year",
    "part_time": False,
    "location": "Houston, USA",
    "latitude": 29.7604,
    "longitude": -95.3698
  },
  {
    "company_name": "Tech Innovations Ltd.",
    "job_name": "Machine Learning Engineer",
    "job_description": "Develop machine learning models and algorithms for data analysis and AI applications.",
    "duration": "Full-time",
    "when_needed": "Immediate",
    "average_pay": "$90,000 per year",
    "part_time": False,
    "location": "Bengaluru, India",
    "latitude": 12.9716,
    "longitude": 77.5946
  },
  {
    "company_name": "Eco-Friendly Homes Ltd.",
    "job_name": "Sustainable Architect",
    "job_description": "Design environmentally friendly and energy-efficient buildings.",
    "duration": "Full-time",
    "when_needed": "1 month from now",
    "average_pay": "$80,000 per year",
    "part_time": False,
    "location": "Stockholm, Sweden",
    "latitude": 59.3293,
    "longitude": 18.0686
  },
  {
    "company_name": "Travel Adventures Ltd.",
    "job_name": "Tour Guide",
    "job_description": "Lead tourists on exciting journeys and provide historical and cultural insights.",
    "duration": "Part-time",
    "when_needed": "2 weeks from now",
    "average_pay": "$30,000 per year (part-time)",
    "part_time": True,
    "location": "Cusco, Peru",
    "latitude": -13.5319,
    "longitude": -71.9675
  },
  {
    "company_name": "Global Environmental Coalition",
    "job_name": "Environmental Activist",
    "job_description": "Advocate for environmental conservation and participate in campaigns.",
    "duration": "Part-time",
    "when_needed": "3 weeks from now",
    "average_pay": "Volunteer position",
    "part_time": True,
    "location": "Cape Town, South Africa",
    "latitude": -33.9249,
    "longitude": 18.4241
  },
  {
    "company_name": "Artisan Bakery & Cafe",
    "job_name": "Baker",
    "job_description": "Prepare delicious bread and pastries for customers to enjoy.",
    "duration": "Full-time",
    "when_needed": "Immediate",
    "average_pay": "$35,000 per year",
    "part_time": False,
    "location": "Paris, France",
    "latitude": 48.8566,
    "longitude": 2.3522
  },
  {
    "company_name": "Tech Startup Innovations",
    "job_name": "Data Scientist",
    "job_description": "Analyze and interpret complex data to support business decision-making.",
    "duration": "Full-time",
    "when_needed": "ASAP",
    "average_pay": "$95,000 per year",
    "part_time": False,
    "location": "San Francisco, USA",
    "latitude": 37.7749,
    "longitude": -122.4194
  },
  {
    "company_name": "Healthcare Innovations Ltd.",
    "job_name": "Radiologist",
    "job_description": "Diagnose and interpret medical images to aid in patient care.",
    "duration": "Full-time",
    "when_needed": "2 weeks from now",
    "average_pay": "$120,000 per year",
    "part_time": False,
    "location": "Melbourne, Australia",
    "latitude": -37.8136,
    "longitude": 144.9631
  },
  {
    "company_name": "Fintech Innovations",
    "job_name": "Blockchain Developer",
    "job_description": "Build and maintain blockchain applications and smart contracts.",
    "duration": "Full-time",
    "when_needed": "Immediate",
    "average_pay": "$85,000 per year",
    "part_time": False,
    "location": "Tokyo, Japan",
    "latitude": 35.682839,
    "longitude": 139.759455
  },
  {
    "company_name": "Green Energy Corporation",
    "job_name": "Wind Turbine Technician",
    "job_description": "Maintain and repair wind turbines to ensure renewable energy production.",
    "duration": "Full-time",
    "when_needed": "1 month from now",
    "average_pay": "$50,000 per year",
    "part_time": False,
    "location": "Berlin, Germany",
    "latitude": 52.5200,
    "longitude": 13.4050
  },
  {
    "company_name": "Renewable Energy Solutions",
    "job_name": "Solar Panel Installer",
    "job_description": "Install and maintain solar panels and renewable energy systems.",
    "duration": "Full-time",
    "when_needed": "Immediate",
    "average_pay": "$45,000 per year",
    "part_time": False,
    "location": "Mexico City, Mexico",
    "latitude": 19.4326,
    "longitude": -99.1332
  },
  {
    "company_name": "Digital Marketing Pro",
    "job_name": "Social Media Manager",
    "job_description": "Manage social media accounts, create content, and engage with the audience.",
    "duration": "Full-time",
    "when_needed": "ASAP",
    "average_pay": "$60,000 per year",
    "part_time": False,
    "location": "São Paulo, Brazil",
    "latitude": -23.5505,
    "longitude": -46.6333
  },
  {
    "company_name": "EcoTech Innovations",
    "job_name": "Environmental Educator",
    "job_description": "Educate the public about environmental issues and promote sustainable practices.",
    "duration": "Part-time",
    "when_needed": "2 weeks from now",
    "average_pay": "$25,000 per year (part-time)",
    "part_time": True,
    "location": "Cape Town, South Africa",
    "latitude": -33.9249,
    "longitude": 18.4241
  },
  {
    "company_name": "Global Shipping Co.",
    "job_name": "Logistics Coordinator",
    "job_description": "Coordinate and manage the logistics of shipping and transportation.",
    "duration": "Full-time",
    "when_needed": "1 month from now",
    "average_pay": "$55,000 per year",
    "part_time": False,
    "location": "Shanghai, China",
    "latitude": 31.2304,
    "longitude": 121.4737
  },
  {
    "company_name": "Tech Startup Innovations",
    "job_name": "UX/UI Designer",
    "job_description": "Design user-friendly interfaces and create compelling user experiences.",
    "duration": "Full-time",
    "when_needed": "ASAP",
    "average_pay": "$70,000 per year",
    "part_time": False,
    "location": "London, UK",
    "latitude": 51.5074,
    "longitude": -0.1278
  },
  {
    "company_name": "Creative Web Studios",
    "job_name": "Web Developer",
    "job_description": "Develop and maintain websites and web applications using modern technologies.",
    "duration": "Full-time",
    "when_needed": "Immediate",
    "average_pay": "$65,000 per year",
    "part_time": False,
    "location": "New York, USA",
    "latitude": 40.7128,
    "longitude": -74.0060
  },
  {
    "company_name": "Biotech Innovations Inc.",
    "job_name": "Biotech Research Scientist",
    "job_description": "Conduct research in biotechnology and contribute to scientific advancements.",
    "duration": "Full-time",
    "when_needed": "ASAP",
    "average_pay": "$80,000 per year",
    "part_time": False,
    "location": "Stockholm, Sweden",
    "latitude": 59.3293,
    "longitude": 18.0686
  },
  {
    "company_name": "Educational Innovations Ltd.",
    "job_name": "Online Tutor (Physics)",
    "job_description": "Provide online physics tutoring to students of various levels.",
    "duration": "Part-time",
    "when_needed": "2 weeks from now",
    "average_pay": "$40 per hour (part-time)",
    "part_time": True,
    "location": "Mumbai, India",
    "latitude": 19.0760,
    "longitude": 72.8777
  },
  {
    "company_name": "Digital Health Solutions",
    "job_name": "Telemedicine Physician",
    "job_description": "Provide remote medical consultations to patients using telemedicine technology.",
    "duration": "Full-time",
    "when_needed": "Immediate",
    "average_pay": "$120,000 per year",
    "part_time": False,
    "location": "San Francisco, USA",
    "latitude": 37.7749,
    "longitude": -122.4194
  },
  {
    "company_name": "AI Research Institute",
    "job_name": "Machine Learning Researcher",
    "job_description": "Conduct cutting-edge research in the field of machine learning and artificial intelligence.",
    "duration": "Full-time",
    "when_needed": "1 month from now",
    "average_pay": "$90,000 per year",
    "part_time": False,
    "location": "Bengaluru, India",
    "latitude": 12.9716,
    "longitude": 77.5946
  },
  {
    "company_name": "EcoTech Innovations",
    "job_name": "Renewable Energy Consultant",
    "job_description": "Advise clients on renewable energy solutions and sustainable practices.",
    "duration": "Full-time",
    "when_needed": "ASAP",
    "average_pay": "$75,000 per year",
    "part_time": False,
    "location": "Copenhagen, Denmark",
    "latitude": 55.6761,
    "longitude": 12.5683
  },
  {
    "company_name": "Green Living Co.",
    "job_name": "Sustainability Analyst",
    "job_description": "Analyze and report on sustainability initiatives and their impact.",
    "duration": "Full-time",
    "when_needed": "Immediate",
    "average_pay": "$60,000 per year",
    "part_time": False,
    "location": "Vancouver, Canada",
    "latitude": 49.2827,
    "longitude": -123.1207
  },
  {
    "company_name": "Tech Innovations Ltd.",
    "job_name": "Cybersecurity Consultant",
    "job_description": "Provide expert cybersecurity consulting to clients for threat protection.",
    "duration": "Full-time",
    "when_needed": "2 weeks from now",
    "average_pay": "$85,000 per year",
    "part_time": False,
    "location": "Berlin, Germany",
    "latitude": 52.5200,
    "longitude": 13.4050
  },
  {
    "company_name": "Digital Marketing Pro",
    "job_name": "SEO Specialist",
    "job_description": "Optimize websites for search engines and improve online visibility.",
    "duration": "Full-time",
    "when_needed": "1 month from now",
    "average_pay": "$55,000 per year",
    "part_time": False,
    "location": "Paris, France",
    "latitude": 48.8566,
    "longitude": 2.3522
  },
  {
    "company_name": "Space Exploration Technologies",
    "job_name": "Mission Control Specialist",
    "job_description": "Oversee space missions and ensure their success from mission control.",
    "duration": "Full-time",
    "when_needed": "ASAP",
    "average_pay": "$70,000 per year",
    "part_time": False,
    "location": "Houston, USA",
    "latitude": 29.7604,
    "longitude": -95.3698
  },
  {
    "company_name": "Healthcare Innovations Ltd.",
    "job_name": "Medical Researcher",
    "job_description": "Conduct medical research studies and contribute to advancements in healthcare.",
    "duration": "Full-time",
    "when_needed": "Immediate",
    "average_pay": "$80,000 per year",
    "part_time": False,
    "location": "Melbourne, Australia",
    "latitude": -37.8136,
    "longitude": 144.9631
  },
  {
    "company_name": "Fashion Forward Designs",
    "job_name": "Fashion Stylist",
    "job_description": "Style models, celebrities, or clients for fashion shoots and events.",
    "duration": "Full-time",
    "when_needed": "2 weeks from now",
    "average_pay": "$40,000 per year",
    "part_time": False,
    "location": "Milan, Italy",
    "latitude": 45.4642,
    "longitude": 9.1900
  },
  {
    "company_name": "Eco-Friendly Homes Ltd.",
    "job_name": "Green Building Inspector",
    "job_description": "Inspect buildings for green certifications and sustainability compliance.",
    "duration": "Full-time",
    "when_needed": "Immediate",
    "average_pay": "$55,000 per year",
    "part_time": False,
    "location": "Stockholm, Sweden",
    "latitude": 59.3293,
    "longitude": 18.0686
  },
  {
    "company_name": "Artisan Bakery & Cafe",
    "job_name": "Pastry Chef",
    "job_description": "Create delectable pastries and desserts for a bakery and cafe.",
    "duration": "Full-time",
    "when_needed": "1 month from now",
    "average_pay": "$45,000 per year",
    "part_time": False,
    "location": "Tokyo, Japan",
    "latitude": 35.682839,
    "longitude": 139.759455
  },
  {
    "company_name": "Global Shipping Co.",
    "job_name": "Freight Broker",
    "job_description": "Coordinate shipments and connect carriers with shippers for transportation.",
    "duration": "Full-time",
    "when_needed": "3 weeks from now",
    "average_pay": "$50,000 per year",
    "part_time": False,
    "location": "Los Angeles, USA",
    "latitude": 34.0522,
    "longitude": -118.2437
  },
  {
    "company_name": "Global Tech Innovations",
    "job_name": "Artificial Intelligence Engineer",
    "job_description": "Develop AI algorithms and systems for various applications.",
    "duration": "Full-time",
    "when_needed": "ASAP",
    "average_pay": "$90,000 per year",
    "part_time": False,
    "location": "Beijing, China",
    "latitude": 39.9042,
    "longitude": 116.4074
  },
  {
    "company_name": "Digital Media Productions",
    "job_name": "Video Producer",
    "job_description": "Plan and oversee video production, from concept to final edit.",
    "duration": "Full-time",
    "when_needed": "Immediate",
    "average_pay": "$70,000 per year",
    "part_time": False,
    "location": "Los Angeles, USA",
    "latitude": 34.0522,
    "longitude": -118.2437
  },
  {
    "company_name": "Tech Innovations Ltd.",
    "job_name": "Data Analyst",
    "job_description": "Analyze and interpret data to help businesses make informed decisions.",
    "duration": "Full-time",
    "when_needed": "2 weeks from now",
    "average_pay": "$60,000 per year",
    "part_time": False,
    "location": "Berlin, Germany",
    "latitude": 52.5200,
    "longitude": 13.4050
  },
  {
    "company_name": "Global Marketing Agency",
    "job_name": "Content Marketing Manager",
    "job_description": "Create and execute content marketing strategies for clients.",
    "duration": "Full-time",
    "when_needed": "1 month from now",
    "average_pay": "$65,000 per year",
    "part_time": False,
    "location": "New York, USA",
    "latitude": 40.7128,
    "longitude": -74.0060
  },
  {
    "company_name": "Digital Health Solutions",
    "job_name": "Clinical Data Scientist",
    "job_description": "Analyze clinical data to support medical research and decision-making.",
    "duration": "Full-time",
    "when_needed": "Immediate",
    "average_pay": "$75,000 per year",
    "part_time": False,
    "location": "London, UK",
    "latitude": 51.5074,
    "longitude": -0.1278
  },
  {
    "company_name": "Fashion Forward Designs",
    "job_name": "Fashion Photographer",
    "job_description": "Capture images of fashion models and clothing for editorial and commercial use.",
    "duration": "Full-time",
    "when_needed": "3 weeks from now",
    "average_pay": "$55,000 per year",
    "part_time": False,
    "location": "Paris, France",
    "latitude": 48.8566,
    "longitude": 2.3522
  },
  {
    "company_name": "Global Environmental Coalition",
    "job_name": "Wildlife Conservationist",
    "job_description": "Contribute to the protection and conservation of endangered species and ecosystems.",
    "duration": "Full-time",
    "when_needed": "ASAP",
    "average_pay": "$50,000 per year",
    "part_time": False,
    "location": "Nairobi, Kenya",
    "latitude": -1.286389,
    "longitude": 36.817223
  },
  {
    "company_name": "Artistic Creations Inc.",
    "job_name": "Fine Artist",
    "job_description": "Create original artwork for exhibitions, galleries, and clients.",
    "duration": "Full-time",
    "when_needed": "2 weeks from now",
    "average_pay": "$40,000 per year",
    "part_time": False,
    "location": "Milan, Italy",
    "latitude": 45.4642,
    "longitude": 9.1900
  },
  {
    "company_name": "Global Shipping Co.",
    "job_name": "Supply Chain Manager",
    "job_description": "Manage the end-to-end supply chain process for the company's products.",
    "duration": "Full-time",
    "when_needed": "Immediate",
    "average_pay": "$70,000 per year",
    "part_time": False,
    "location": "Shanghai, China",
    "latitude": 31.2304,
    "longitude": 121.4737
  },
  {
    "company_name": "Digital Media Innovations",
    "job_name": "Digital Illustrator",
    "job_description": "Create digital illustrations for books, magazines, and digital media content.",
    "duration": "Part-time",
    "when_needed": "1 month from now",
    "average_pay": "$35,000 per year (part-time)",
    "part_time": True,
    "location": "Sydney, Australia",
    "latitude": -33.8688,
    "longitude": 151.2093
  }
])